### ISSUE TITLE
suggestion: Delete command messages and command prompts also make it all in one action

### ISSUE THREAD

**Issue by NftNub** [Darkgoatie/Aether#2]
Delete command messages and command prompts when entered.
Specifically for Auctions to keep a clean auction room goin
user: >astart 500 example
Aether: how long would you like the auction to last?
user: 50h
Aether: Reserve price?  (Reserve means item does not sell if it does not reach desired price)
user: 700
Aether: Buyout Price? (means the price in which the person instantly buys an item/wins the auction)
none
Aether: in what increments would you like the bid to be?
user: 5
Aether: sniping allowed?  (last second bids)
user:yes or no
*if no then auction continues for another 5-10mins
Aether: what channel would you like the auction to be posted in? (optional if you'd like to implement it)
user: #auction room 1

*Bot posts auction in chosen or dedicated channel, deletes the entire conversation is had with the user as well as its own messages*

also ability to load an image maybe but that's optional

**Comment by Darkgoatie** [comment]
That won't be added, all features are already avaliable in different commands. Also don't open this as an issue, issues are only for bugs. You can use [Pull requests](https://github.com/Darkgoatie/Aether/pulls) to suggest anything, ask for an update.
