### ISSUE TITLE
Sticky Messages

### ISSUE THREAD

**Issue by Lox504** [Darkgoatie/Aether#3]
I've use aether for a long time and I realise that Aether's sticky messages is not applying to the bot messages, I wish Dark can fix that so it'll be way more convenient.

**Comment by Darkgoatie** [comment]
Well that's right and it's something made on purpose. For performance issues we're not letting aether respond to bots because some bots have features like: `autofeed` , `autopost` or `random pokemon spawning events`. That'll create an auto message loop which will corrupt memory usage.
